/**
 * GlobeTrotter catalog seed data.
 * 15 cities across different countries, each with 6-8 activities
 * spread across sightseeing, food, adventure, culture, and relaxation.
 */
export const seedCities = [
  {
    name: "Paris",
    country: "France",
    costIndex: 1.35,
    popularityScore: 98,
    imageUrl: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34",
    activities: [
      { name: "Eiffel Tower Summit", category: "sightseeing", cost: 29.0, durationHours: 2.5, description: "Skip-the-line access to the top of the Eiffel Tower with panoramic city views.", imageUrl: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f" },
      { name: "Louvre Museum Highlights", category: "culture", cost: 22.0, durationHours: 4.0, description: "Guided tour of the Louvre including the Mona Lisa and classical masterpieces.", imageUrl: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a" },
      { name: "Montmartre Food Walk", category: "food", cost: 65.0, durationHours: 3.0, description: "Taste cheese, wine, and pastries while exploring Montmartre's cobblestone streets.", imageUrl: "https://images.unsplash.com/photo-1559336909-9c6e4e2b6c4e" },
      { name: "Seine River Cruise", category: "relaxation", cost: 18.0, durationHours: 1.5, description: "Evening cruise along the Seine with views of Notre-Dame and the Louvre.", imageUrl: "https://images.unsplash.com/photo-1508057197833-0b6c4e2b6c4e" },
      { name: "Versailles Bike Tour", category: "adventure", cost: 55.0, durationHours: 5.0, description: "Cycle through the palace gardens and surrounding countryside of Versailles.", imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa" },
      { name: "Arc de Triomphe Rooftop", category: "sightseeing", cost: 16.0, durationHours: 1.5, description: "Climb to the top of the Arc de Triomphe for views down the Champs-Elysees.", imageUrl: "https://images.unsplash.com/photo-1431277652768-9e6e4e2b6c4e" },
      { name: "Musee d'Orsay Impressionists", category: "culture", cost: 18.0, durationHours: 3.0, description: "Self-guided visit to Monet, Renoir, and Van Gogh in a former railway station.", imageUrl: "https://images.unsplash.com/photo-1566127445079-442a8f8e8e8e" },
    ],
  },
  {
    name: "Tokyo",
    country: "Japan",
    costIndex: 1.25,
    popularityScore: 96,
    imageUrl: "https://images.unsplash.com/photo-1540959733332-eab4deab2af3",
    activities: [
      { name: "Senso-ji Temple Visit", category: "culture", cost: 0.0, durationHours: 2.0, description: "Explore Tokyo's oldest Buddhist temple in the Asakusa district.", imageUrl: "https://images.unsplash.com/photo-1545569341-9f1f5c2c3c3c" },
      { name: "Tsukiji Outer Market Tasting", category: "food", cost: 45.0, durationHours: 2.5, description: "Sample fresh sushi, tamagoyaki, and street snacks at the famous market.", imageUrl: "https://images.unsplash.com/photo-1579871494447-81f6e4e2b6c4" },
      { name: "Shibuya Sky Observatory", category: "sightseeing", cost: 24.0, durationHours: 1.5, description: "Open-air rooftop views over Shibuya Crossing and the Tokyo skyline.", imageUrl: "https://images.unsplash.com/photo-1549692520-9f1f5c2c3c3c" },
      { name: "Mount Takao Day Hike", category: "adventure", cost: 12.0, durationHours: 6.0, description: "Half-day hike through forest trails with optional cable car descent.", imageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e712f1f5" },
      { name: "Oedo Onsen Monogatari", category: "relaxation", cost: 38.0, durationHours: 3.0, description: "Traditional hot-spring theme park experience with multiple bath types.", imageUrl: "https://images.unsplash.com/photo-1528164344705-475426870976" },
      { name: "TeamLab Borderless", category: "culture", cost: 32.0, durationHours: 2.5, description: "Immersive digital art museum with interactive light installations.", imageUrl: "https://images.unsplash.com/photo-1560835621-4e6e4e2b6c4e" },
      { name: "Ramen Alley Tour", category: "food", cost: 55.0, durationHours: 3.0, description: "Guided tasting of regional ramen styles across three acclaimed shops.", imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624" },
      { name: "Akihabara Electric Town", category: "sightseeing", cost: 0.0, durationHours: 2.0, description: "Self-guided wander through anime shops, arcades, and gadget stores.", imageUrl: "https://images.unsplash.com/photo-1480796928339-3f1f5c2c3c3c" },
    ],
  },
  {
    name: "New York",
    country: "United States",
    costIndex: 1.45,
    popularityScore: 97,
    imageUrl: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9",
    activities: [
      { name: "Statue of Liberty & Ellis Island", category: "sightseeing", cost: 24.0, durationHours: 4.0, description: "Ferry and museum access to two iconic symbols of American immigration.", imageUrl: "https://images.unsplash.com/photo-1485871981521-4e6e4e2b6c4e" },
      { name: "Broadway Matinee Show", category: "culture", cost: 120.0, durationHours: 2.5, description: "Orchestra-seat ticket to a current Broadway production.", imageUrl: "https://images.unsplash.com/photo-1507676184212-4e6e4e2b6c4e" },
      { name: "Brooklyn Pizza & Bagel Crawl", category: "food", cost: 48.0, durationHours: 3.0, description: "Sample legendary New York pizza slices and hand-rolled bagels.", imageUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591" },
      { name: "Central Park Bike Rental", category: "adventure", cost: 35.0, durationHours: 2.0, description: "Rent a bike and loop the park's reservoirs, meadows, and bridges.", imageUrl: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e" },
      { name: "High Line Stroll", category: "relaxation", cost: 0.0, durationHours: 1.5, description: "Leisurely walk along the elevated park built on a historic freight rail line.", imageUrl: "https://images.unsplash.com/photo-1467269209871-e00806667343" },
      { name: "Empire State Building", category: "sightseeing", cost: 44.0, durationHours: 2.0, description: "Express pass to the 86th-floor open-air observation deck.", imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e4e6e" },
      { name: "MoMA Modern Art Collection", category: "culture", cost: 28.0, durationHours: 3.0, description: "Visit Warhol, Van Gogh, and contemporary installations at the Museum of Modern Art.", imageUrl: "https://images.unsplash.com/photo-1561214115-f3f6e4e2b6c4" },
    ],
  },
  {
    name: "Barcelona",
    country: "Spain",
    costIndex: 1.05,
    popularityScore: 92,
    imageUrl: "https://images.unsplash.com/photo-1583422409516-8fd055211328",
    activities: [
      { name: "Sagrada Familia Guided Tour", category: "sightseeing", cost: 36.0, durationHours: 2.5, description: "Skip-the-line entry and tower access to Gaudi's unfinished basilica.", imageUrl: "https://images.unsplash.com/photo-1583422409516-8fd055211328" },
      { name: "Park Guell", category: "culture", cost: 12.0, durationHours: 2.0, description: "Explore Gaudi's mosaic terraces and panoramic views over Barcelona.", imageUrl: "https://images.unsplash.com/photo-1558642452-9d2a4deb7b62" },
      { name: "La Boqueria Tapas Tour", category: "food", cost: 52.0, durationHours: 2.5, description: "Market tasting of jamon, pan con tomate, and Catalan vermouth.", imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1" },
      { name: "Coastal Kayaking", category: "adventure", cost: 45.0, durationHours: 3.0, description: "Paddle along the Costa Brava with cliff-side coves and snorkel stops.", imageUrl: "https://images.unsplash.com/photo-1530549387789-4c1017266635" },
      { name: "Barceloneta Beach Afternoon", category: "relaxation", cost: 15.0, durationHours: 3.0, description: "Sun lounger rental and chilled afternoon by the Mediterranean.", imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e" },
      { name: "Gothic Quarter Walking Tour", category: "sightseeing", cost: 22.0, durationHours: 2.0, description: "Discover Roman walls, hidden plazas, and medieval alleyways.", imageUrl: "https://images.unsplash.com/photo-1562883676-4e6e4e2b6c4e" },
      { name: "Flamenco Show & Dinner", category: "culture", cost: 68.0, durationHours: 2.5, description: "Authentic tablao performance with a three-course Catalan dinner.", imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819" },
    ],
  },
  {
    name: "Rome",
    country: "Italy",
    costIndex: 1.1,
    popularityScore: 94,
    imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5",
    activities: [
      { name: "Colosseum & Roman Forum", category: "sightseeing", cost: 24.0, durationHours: 3.0, description: "Skip-the-line access to ancient Rome's amphitheater and civic heart.", imageUrl: "https://images.unsplash.com/photo-1552832230-c0197dd311b5" },
      { name: "Vatican Museums & Sistine Chapel", category: "culture", cost: 32.0, durationHours: 4.0, description: "Early-entry tour of Michelangelo's ceiling and the papal art collections.", imageUrl: "https://images.unsplash.com/photo-1555992336-03a23c7b0877" },
      { name: "Trastevere Food Tour", category: "food", cost: 58.0, durationHours: 3.0, description: "Suppli, cacio e pepe, and gelato in Rome's most charming neighborhood.", imageUrl: "https://images.unsplash.com/photo-1598866594230-a7c127049805" },
      { name: "Appian Way Cycling", category: "adventure", cost: 40.0, durationHours: 4.0, description: "Cycle the ancient road past catacombs, aqueducts, and countryside villas.", imageUrl: "https://images.unsplash.com/photo-1571068316344-75bc76f77890" },
      { name: "Villa Borghese Gardens", category: "relaxation", cost: 8.0, durationHours: 2.0, description: "Rowboat rental and shaded strolls through Rome's largest public park.", imageUrl: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9" },
      { name: "Trevi Fountain & Pantheon Walk", category: "sightseeing", cost: 0.0, durationHours: 2.0, description: "Self-guided route through Rome's most photogenic landmarks.", imageUrl: "https://images.unsplash.com/photo-1529260830197-4e6e4e2b6c4e" },
      { name: "Opera at Terme di Caracalla", category: "culture", cost: 75.0, durationHours: 3.0, description: "Open-air opera performance among ancient Roman bath ruins.", imageUrl: "https://images.unsplash.com/photo-1507831417534-4e6e4e2b6c4e" },
      { name: "Espresso & Pastry Masterclass", category: "food", cost: 42.0, durationHours: 2.0, description: "Learn to pull espresso and bake cornetti with a local barista.", imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085" },
    ],
  },
  {
    name: "Bangkok",
    country: "Thailand",
    costIndex: 0.55,
    popularityScore: 88,
    imageUrl: "https://images.unsplash.com/photo-1563492065-454bf2155e9a",
    activities: [
      { name: "Grand Palace & Wat Phra Kaew", category: "sightseeing", cost: 18.0, durationHours: 3.0, description: "Visit Thailand's most sacred temple and the former royal residence.", imageUrl: "https://images.unsplash.com/photo-1563492065-454bf2155e9a" },
      { name: "Chinatown Street Food Night", category: "food", cost: 25.0, durationHours: 3.0, description: "Guided feast of pad thai, mango sticky rice, and boat noodles.", imageUrl: "https://images.unsplash.com/photo-1559336909-9c6e4e2b6c4e" },
      { name: "Muay Thai Training Session", category: "adventure", cost: 30.0, durationHours: 2.0, description: "Beginner-friendly session at a historic Bangkok boxing gym.", imageUrl: "https://images.unsplash.com/photo-1594736797933-4e6e4e2b6c4e" },
      { name: "Traditional Thai Massage", category: "relaxation", cost: 20.0, durationHours: 1.5, description: "Authentic Thai massage at a certified wellness spa in Silom.", imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874" },
      { name: "Jim Thompson House Museum", category: "culture", cost: 12.0, durationHours: 2.0, description: "Tour the teakwood home of the American silk entrepreneur.", imageUrl: "https://images.unsplash.com/photo-1528183429752-a97d0bf99b5a" },
      { name: "Chao Phraya River Dinner Cruise", category: "relaxation", cost: 35.0, durationHours: 2.5, description: "Buffet dinner while gliding past illuminated temples and bridges.", imageUrl: "https://images.unsplash.com/photo-1528183429752-a97d0bf99b5b" },
      { name: "Floating Market Day Trip", category: "sightseeing", cost: 28.0, durationHours: 5.0, description: "Visit Damnoen Saduak's colorful canal market outside the city.", imageUrl: "https://images.unsplash.com/photo-1528183429752-a97d0bf99b5c" },
    ],
  },
  {
    name: "Istanbul",
    country: "Turkey",
    costIndex: 0.65,
    popularityScore: 85,
    imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200",
    activities: [
      { name: "Hagia Sophia & Blue Mosque", category: "sightseeing", cost: 15.0, durationHours: 3.0, description: "Guided visit to two masterpieces spanning Byzantine and Ottoman eras.", imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200" },
      { name: "Grand Bazaar Shopping Tour", category: "culture", cost: 0.0, durationHours: 2.5, description: "Navigate 4,000 shops of spices, carpets, and Turkish ceramics.", imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7201" },
      { name: "Bosphorus Fish Restaurant", category: "food", cost: 38.0, durationHours: 2.0, description: "Fresh grilled sea bass with meze overlooking the strait.", imageUrl: "https://images.unsplash.com/photo-1559336909-9c6e4e2b6c4f" },
      { name: "Hot Air Balloon (Cappadocia Day Trip)", category: "adventure", cost: 180.0, durationHours: 10.0, description: "Sunrise balloon flight over fairy chimneys with round-trip transfer.", imageUrl: "https://images.unsplash.com/photo-1506905925346-21b4e3a7200" },
      { name: "Turkish Hammam Experience", category: "relaxation", cost: 45.0, durationHours: 2.0, description: "Traditional scrub and foam massage at a historic bathhouse.", imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef" },
      { name: "Topkapi Palace Treasury", category: "culture", cost: 20.0, durationHours: 3.0, description: "Explore Ottoman sultans' palace, harem, and jewel collections.", imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7202" },
      { name: "Galata Tower Sunset", category: "sightseeing", cost: 12.0, durationHours: 1.5, description: "Panoramic Golden Horn views from the medieval Genoese tower.", imageUrl: "https://images.unsplash.com/photo-1524231757912-21f4fe3a7203" },
    ],
  },
  {
    name: "Sydney",
    country: "Australia",
    costIndex: 1.3,
    popularityScore: 86,
    imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d8",
    activities: [
      { name: "Sydney Opera House Tour", category: "sightseeing", cost: 32.0, durationHours: 1.5, description: "Behind-the-scenes tour of the sails and concert halls.", imageUrl: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d8" },
      { name: "Harbour Bridge Climb", category: "adventure", cost: 174.0, durationHours: 3.5, description: "Guided summit climb with 360-degree views of the harbour.", imageUrl: "https://images.unsplash.com/photo-1523482580672-f5041c1e1f5a" },
      { name: "Bondi to Coogee Coastal Walk", category: "relaxation", cost: 0.0, durationHours: 3.0, description: "Scenic cliffside walk past beaches, pools, and ocean lookouts.", imageUrl: "https://images.unsplash.com/photo-1506905925346-21b4e3a7201" },
      { name: "Rocks Market & Seafood Lunch", category: "food", cost: 48.0, durationHours: 2.5, description: "Harbour-side oysters, fish and chips, and local craft beer.", imageUrl: "https://images.unsplash.com/photo-1559336909-9c6e4e2b6c50" },
      { name: "Art Gallery of NSW", category: "culture", cost: 0.0, durationHours: 2.5, description: "Australian and Aboriginal art in a grand parkland gallery.", imageUrl: "https://images.unsplash.com/photo-1561214115-f3f6e4e2b6c50" },
      { name: "Manly Beach Surf Lesson", category: "adventure", cost: 65.0, durationHours: 2.0, description: "Beginner surf lesson on one of Sydney's favorite northern beaches.", imageUrl: "https://images.unsplash.com/photo-1502680390469-be688c862258" },
      { name: "Taronga Zoo Visit", category: "sightseeing", cost: 38.0, durationHours: 4.0, description: "Ferry and entry to the harbour-side zoo with koala encounters.", imageUrl: "https://images.unsplash.com/photo-1437622367822-338a3d087ca2" },
    ],
  },
  {
    name: "Cape Town",
    country: "South Africa",
    costIndex: 0.7,
    popularityScore: 78,
    imageUrl: "https://images.unsplash.com/photo-1580060839134-75a3adaa8d4b",
    activities: [
      { name: "Table Mountain Cableway", category: "sightseeing", cost: 28.0, durationHours: 3.0, description: "Return cable car to the flat-topped mountain overlooking the city.", imageUrl: "https://images.unsplash.com/photo-1580060839134-75a3adaa8d4b" },
      { name: "Cape Peninsula Tour", category: "adventure", cost: 55.0, durationHours: 8.0, description: "Drive to Cape Point, Boulders Beach penguins, and Chapman's Peak.", imageUrl: "https://images.unsplash.com/photo-1516026672322-bc52d690a55d" },
      { name: "Bo-Kaap Cooking Class", category: "food", cost: 42.0, durationHours: 3.0, description: "Learn Cape Malay curries and samoosas in the colorful hillside quarter.", imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4d" },
      { name: "Kirstenbosch Gardens Picnic", category: "relaxation", cost: 10.0, durationHours: 2.5, description: "Botanical garden stroll with mountain backdrop and shaded lawns.", imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b" },
      { name: "Robben Island Tour", category: "culture", cost: 30.0, durationHours: 4.0, description: "Ferry to the former prison where Nelson Mandela was held.", imageUrl: "https://images.unsplash.com/photo-1523805009345-7448845a9e53" },
      { name: "V&A Waterfront Sunset", category: "relaxation", cost: 0.0, durationHours: 2.0, description: "Harbour-side stroll, street performers, and ocean views at dusk.", imageUrl: "https://images.unsplash.com/photo-1580060839134-75a3adaa8d4c" },
      { name: "Township Art & Music Walk", category: "culture", cost: 35.0, durationHours: 3.0, description: "Community-led tour of local galleries, murals, and live jazz.", imageUrl: "https://images.unsplash.com/photo-1516026672322-bc52d690a55e" },
    ],
  },
  {
    name: "Prague",
    country: "Czech Republic",
    costIndex: 0.75,
    popularityScore: 82,
    imageUrl: "https://images.unsplash.com/photo-1541849548769-f548a6d3c103",
    activities: [
      { name: "Prague Castle Complex", category: "sightseeing", cost: 18.0, durationHours: 3.0, description: "Tour St. Vitus Cathedral, Golden Lane, and royal courtyards.", imageUrl: "https://images.unsplash.com/photo-1541849548769-f548a6d3c103" },
      { name: "Old Town & Astronomical Clock", category: "sightseeing", cost: 0.0, durationHours: 2.0, description: "Self-guided walk across Charles Bridge to the medieval square.", imageUrl: "https://images.unsplash.com/photo-1541849548769-f548a6d3c104" },
      { name: "Czech Beer Tasting", category: "food", cost: 28.0, durationHours: 2.0, description: "Sample pilsners and dark lagers at three historic pubs.", imageUrl: "https://images.unsplash.com/photo-1608270586620-248524c67de9" },
      { name: "Vltava Kayak Rental", category: "adventure", cost: 22.0, durationHours: 2.5, description: "Paddle through the city center with views of riverside architecture.", imageUrl: "https://images.unsplash.com/photo-1530549387789-4c1017266636" },
      { name: "Karlovy Lazne Spa Evening", category: "relaxation", cost: 25.0, durationHours: 2.0, description: "Thermal pool and sauna session at a historic bath complex.", imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbece0" },
      { name: "Mucha Museum", category: "culture", cost: 12.0, durationHours: 1.5, description: "Art Nouveau posters and paintings by Alfons Mucha.", imageUrl: "https://images.unsplash.com/photo-1561214115-f3f6e4e2b6c51" },
      { name: "Traditional Czech Dinner", category: "food", cost: 32.0, durationHours: 2.0, description: "Roast duck, dumplings, and apple strudel in a cellar restaurant.", imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad2" },
    ],
  },
  {
    name: "Dubai",
    country: "United Arab Emirates",
    costIndex: 1.2,
    popularityScore: 90,
    imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8882c",
    activities: [
      { name: "Burj Khalifa At the Top", category: "sightseeing", cost: 45.0, durationHours: 2.0, description: "Observation deck on the world's tallest building at sunset.", imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8882c" },
      { name: "Desert Safari & Dune Bashing", category: "adventure", cost: 65.0, durationHours: 6.0, description: "4x4 dunes, camel ride, BBQ dinner, and belly dancing under the stars.", imageUrl: "https://images.unsplash.com/photo-1451337516015-6b6e4e2b6c51" },
      { name: "Dubai Mall Aquarium", category: "sightseeing", cost: 38.0, durationHours: 2.0, description: "Walk through the tunnel tank among sharks and rays.", imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8882d" },
      { name: "Al Fahidi Heritage Walk", category: "culture", cost: 0.0, durationHours: 2.0, description: "Explore wind-tower houses, souks, and the Dubai Museum quarter.", imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8882e" },
      { name: "Luxury Spa at Palm Jumeirah", category: "relaxation", cost: 120.0, durationHours: 2.5, description: "Full-body treatment with Arabian oils at a five-star resort spa.", imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbece1" },
      { name: "Dhow Creek Dinner Cruise", category: "food", cost: 55.0, durationHours: 2.5, description: "Traditional wooden boat buffet with Arabic mezze and grilled meats.", imageUrl: "https://images.unsplash.com/photo-1559336909-9c6e4e2b6c51" },
      { name: "Gold & Spice Souk Tour", category: "culture", cost: 15.0, durationHours: 2.0, description: "Guided visit to Deira's glittering gold market and fragrant spice stalls.", imageUrl: "https://images.unsplash.com/photo-1512453979798-5ea266f8882f" },
      { name: "Skydiving over Palm", category: "adventure", cost: 590.0, durationHours: 3.0, description: "Tandem jump with aerial views of the Palm Jumeirah and Marina.", imageUrl: "https://images.unsplash.com/photo-1502680390469-be688c862259" },
    ],
  },
  {
    name: "Lisbon",
    country: "Portugal",
    costIndex: 0.85,
    popularityScore: 84,
    imageUrl: "https://images.unsplash.com/photo-1555881400-74d7aca95a7f",
    activities: [
      { name: "Belem Tower & Jeronimos", category: "sightseeing", cost: 12.0, durationHours: 3.0, description: "UNESCO monuments of Portugal's Age of Discovery.", imageUrl: "https://images.unsplash.com/photo-1555881400-74d7aca95a7f" },
      { name: "Alfama Fado Night", category: "culture", cost: 38.0, durationHours: 2.5, description: "Intimate fado performance with wine in a historic tavern.", imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd820" },
      { name: "Time Out Market Tasting", category: "food", cost: 35.0, durationHours: 2.0, description: "Sample bacalhau, pasteis de nata, and petiscos from top chefs.", imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad3" },
      { name: "Sintra Day Trip", category: "adventure", cost: 48.0, durationHours: 7.0, description: "Visit Pena Palace, Moorish Castle, and Quinta da Regaleira.", imageUrl: "https://images.unsplash.com/photo-1555881400-74d7aca95a80" },
      { name: "Miradouro Sunset & Wine", category: "relaxation", cost: 18.0, durationHours: 2.0, description: "Watch the sun set over the Tagus with a glass of vinho verde.", imageUrl: "https://images.unsplash.com/photo-1506377247377-2ccd5cedb242" },
      { name: "Tram 28 Ride", category: "sightseeing", cost: 3.0, durationHours: 1.0, description: "Classic yellow tram through Lisbon's steepest and oldest districts.", imageUrl: "https://images.unsplash.com/photo-1555881400-74d7aca95a81" },
      { name: "Tile Painting Workshop", category: "culture", cost: 45.0, durationHours: 2.5, description: "Paint your own azulejo tile with a local ceramic artist.", imageUrl: "https://images.unsplash.com/photo-1561214115-f3f6e4e2b6c52" },
    ],
  },
  {
    name: "Bali",
    country: "Indonesia",
    costIndex: 0.5,
    popularityScore: 87,
    imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4",
    activities: [
      { name: "Tegallalang Rice Terraces", category: "sightseeing", cost: 5.0, durationHours: 3.0, description: "Walk the emerald paddies and swing over the Ubud valley.", imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab4" },
      { name: "Mount Batur Sunrise Trek", category: "adventure", cost: 35.0, durationHours: 6.0, description: "Pre-dawn hike to an active volcano crater with breakfast.", imageUrl: "https://images.unsplash.com/photo-1506905925346-21b4e3a7202" },
      { name: "Balinese Cooking Class", category: "food", cost: 30.0, durationHours: 4.0, description: "Market visit and hands-on class making satay, lawar, and sambal.", imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4e" },
      { name: "Ubud Yoga & Meditation", category: "relaxation", cost: 15.0, durationHours: 1.5, description: "Morning vinyasa session in an open-air jungle studio.", imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b" },
      { name: "Uluwatu Temple & Kecak Dance", category: "culture", cost: 20.0, durationHours: 3.0, description: "Clifftop temple visit followed by a dramatic fire dance at sunset.", imageUrl: "https://images.unsplash.com/photo-1537996194471-e657df975ab5" },
      { name: "Snorkeling at Nusa Penida", category: "adventure", cost: 42.0, durationHours: 8.0, description: "Boat trip to crystal waters with manta ray snorkeling.", imageUrl: "https://images.unsplash.com/photo-1559827260-dc66d52bef19" },
      { name: "Seminyak Beach Club Day", category: "relaxation", cost: 25.0, durationHours: 4.0, description: "Daybed, pool access, and tropical cocktails on the coast.", imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3f" },
    ],
  },
  {
    name: "Reykjavik",
    country: "Iceland",
    costIndex: 1.55,
    popularityScore: 75,
    imageUrl: "https://images.unsplash.com/photo-1529963189033-4e6e4e2b6c52",
    activities: [
      { name: "Golden Circle Tour", category: "sightseeing", cost: 85.0, durationHours: 8.0, description: "Thingvellir, Geysir, and Gullfoss waterfall in one day.", imageUrl: "https://images.unsplash.com/photo-1504829857797-ddff29c27927" },
      { name: "Blue Lagoon Entry", category: "relaxation", cost: 95.0, durationHours: 3.0, description: "Geothermal spa in milky-blue silica-rich waters.", imageUrl: "https://images.unsplash.com/photo-1516026672322-bc52d690a55f" },
      { name: "Northern Lights Hunt", category: "adventure", cost: 70.0, durationHours: 4.0, description: "Evening bus tour chasing aurora borealis away from city lights.", imageUrl: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73" },
      { name: "Harp Concert Hall Tour", category: "culture", cost: 12.0, durationHours: 1.5, description: "Architecture tour of the glass facade inspired by basalt columns.", imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd821" },
      { name: "Icelandic Fish & Lamb Dinner", category: "food", cost: 55.0, durationHours: 2.0, description: "Arctic char, rye bread, and slow-roasted lamb at a harbor restaurant.", imageUrl: "https://images.unsplash.com/photo-1559336909-9c6e4e2b6c52" },
      { name: "Hallgrimskirkja Tower", category: "sightseeing", cost: 8.0, durationHours: 1.0, description: "Elevator to the top of Reykjavik's iconic church for city views.", imageUrl: "https://images.unsplash.com/photo-1529963189033-4e6e4e2b6c53" },
      { name: "Glacier Hiking (Solheimajokull)", category: "adventure", cost: 110.0, durationHours: 5.0, description: "Guided hike on a glacier tongue with crampons and ice axes.", imageUrl: "https://images.unsplash.com/photo-1483347756197-71ef80e95f74" },
    ],
  },
  {
    name: "Buenos Aires",
    country: "Argentina",
    costIndex: 0.6,
    popularityScore: 80,
    imageUrl: "https://images.unsplash.com/photo-1589909202803-3e5302a3e8c8",
    activities: [
      { name: "La Boca & Caminito Walk", category: "sightseeing", cost: 0.0, durationHours: 2.5, description: "Colorful street art, tango dancers, and Boca Juniors stadium exterior.", imageUrl: "https://images.unsplash.com/photo-1589909202803-3e5302a3e8c8" },
      { name: "Tango Show & Dinner", category: "culture", cost: 62.0, durationHours: 3.0, description: "Professional tango performance with Argentine steak dinner.", imageUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd822" },
      { name: "Palermo Food & Wine Tour", category: "food", cost: 40.0, durationHours: 3.0, description: "Empanadas, Malbec, and dulce de leche in Buenos Aires' trendiest barrio.", imageUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad4" },
      { name: "Polo Match Experience", category: "adventure", cost: 75.0, durationHours: 4.0, description: "Watch an elite polo match with wine and asado at an estancia.", imageUrl: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fb" },
      { name: "Japanese Garden Retreat", category: "relaxation", cost: 8.0, durationHours: 2.0, description: "Peaceful stroll through bridges, koi ponds, and bonsai in Palermo.", imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5c" },
      { name: "Recoleta Cemetery Tour", category: "culture", cost: 18.0, durationHours: 2.0, description: "Guided visit to Eva Peron's mausoleum and ornate family tombs.", imageUrl: "https://images.unsplash.com/photo-1589909202803-3e5302a3e8c9" },
      { name: "Asado Cooking Workshop", category: "food", cost: 50.0, durationHours: 3.5, description: "Learn to grill Argentine cuts over open flame with chimichurri.", imageUrl: "https://images.unsplash.com/photo-1556910103-1c02745aae4f" },
      { name: "Delta Tigre Boat Trip", category: "sightseeing", cost: 22.0, durationHours: 4.0, description: "River delta cruise through islands, markets, and stilt houses.", imageUrl: "https://images.unsplash.com/photo-1589909202803-3e5302a3e8ca" },
    ],
  },
];

export const seedCategories = [
  "sightseeing",
  "food",
  "adventure",
  "culture",
  "relaxation",
];
